# Use a lighter version of Node as a parent image
FROM mhart/alpine-node:8.11.4
#FROM iron/node:latest

# Set the working directory to /client
WORKDIR /client

# Copy content into the imageat /client
COPY package*.json /client/
RUN npm install
COPY . /client/

# Use port 3000
EXPOSE 3000

# Run the app when the container launches
CMD ["npm", "start"]
